overwrite: true
schema: "http://localhost:4000/graphql"
documents: "graphql/**/*.graphql"
generates:
  graphql/types.tsx:
    plugins:
      - "typescript"
  graphql/:
    preset: near-operation-file
    presetConfig:
      extension: .gql.tsx
      baseTypesPath: types.ts
    plugins:
      - "typescript-operations"
      - "typescript-urql"
    config:
      withHooks: true
